//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K0ntr0l.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PatternLibraryPath {
            get {
                return ((string)(this["PatternLibraryPath"]));
            }
            set {
                this["PatternLibraryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19200")]
        public int CommsBaudRate {
            get {
                return ((int)(this["CommsBaudRate"]));
            }
            set {
                this["CommsBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FileFilterIndex {
            get {
                return ((int)(this["FileFilterIndex"]));
            }
            set {
                this["FileFilterIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastPatternBrowsePath {
            get {
                return ((string)(this["LastPatternBrowsePath"]));
            }
            set {
                this["LastPatternBrowsePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDumpBrowsePath {
            get {
                return ((string)(this["LastDumpBrowsePath"]));
            }
            set {
                this["LastDumpBrowsePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color NoteColor {
            get {
                return ((global::System.Drawing.Color)(this["NoteColor"]));
            }
            set {
                this["NoteColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color AccentedNoteColor {
            get {
                return ((global::System.Drawing.Color)(this["AccentedNoteColor"]));
            }
            set {
                this["AccentedNoteColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 192, 255")]
        public global::System.Drawing.Color RestColor {
            get {
                return ((global::System.Drawing.Color)(this["RestColor"]));
            }
            set {
                this["RestColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color AccentedRestColor {
            get {
                return ((global::System.Drawing.Color)(this["AccentedRestColor"]));
            }
            set {
                this["AccentedRestColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color SlideColor {
            get {
                return ((global::System.Drawing.Color)(this["SlideColor"]));
            }
            set {
                this["SlideColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreviewPatterns {
            get {
                return ((bool)(this["PreviewPatterns"]));
            }
            set {
                this["PreviewPatterns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int WaitForBytesTimeOut {
            get {
                return ((int)(this["WaitForBytesTimeOut"]));
            }
            set {
                this["WaitForBytesTimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int SerialPortReadWriteTimeout {
            get {
                return ((int)(this["SerialPortReadWriteTimeout"]));
            }
            set {
                this["SerialPortReadWriteTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AdjustTempo {
            get {
                return ((bool)(this["AdjustTempo"]));
            }
            set {
                this["AdjustTempo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdates {
            get {
                return ((bool)(this["CheckForUpdates"]));
            }
            set {
                this["CheckForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int WaitForBytesSleepTime {
            get {
                return ((int)(this["WaitForBytesSleepTime"]));
            }
            set {
                this["WaitForBytesSleepTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowToolTips {
            get {
                return ((bool)(this["ShowToolTips"]));
            }
            set {
                this["ShowToolTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedPatternDoubleClickAction {
            get {
                return ((int)(this["SelectedPatternDoubleClickAction"]));
            }
            set {
                this["SelectedPatternDoubleClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FormPreviewCommsWarning {
            get {
                return ((bool)(this["FormPreviewCommsWarning"]));
            }
            set {
                this["FormPreviewCommsWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("980, 507")]
        public global::System.Drawing.Size PatternLibraryWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["PatternLibraryWindowSize"]));
            }
            set {
                this["PatternLibraryWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState PatternLibraryWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["PatternLibraryWindowState"]));
            }
            set {
                this["PatternLibraryWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int PatternLinbraryColumnNameWidth {
            get {
                return ((int)(this["PatternLinbraryColumnNameWidth"]));
            }
            set {
                this["PatternLinbraryColumnNameWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int PatternLinbraryColumnDescriptionWidth {
            get {
                return ((int)(this["PatternLinbraryColumnDescriptionWidth"]));
            }
            set {
                this["PatternLinbraryColumnDescriptionWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int PatternLinbraryColumnLengthWidth {
            get {
                return ((int)(this["PatternLinbraryColumnLengthWidth"]));
            }
            set {
                this["PatternLinbraryColumnLengthWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int PatternLinbraryColumnTempoWidth {
            get {
                return ((int)(this["PatternLinbraryColumnTempoWidth"]));
            }
            set {
                this["PatternLinbraryColumnTempoWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int PatternLinbraryColumnSourceWidth {
            get {
                return ((int)(this["PatternLinbraryColumnSourceWidth"]));
            }
            set {
                this["PatternLinbraryColumnSourceWidth"] = value;
            }
        }
    }
}
